# Nombre del paquete
package_name: modelo-diabetes

# Archivos de datos
train_data_file: diabetes_train.csv
test_data_file: diabetes_test.csv

# Variables
# Objetivo
target: Diabetes_012

features:
  - HighBP
  - HighChol
  - BMI
  - Age
  - HeartDiseaseorAttack
  - GenHlth
  

temp_features:


# pipelines
pipeline_name: modelo-diabetes
pipeline_save_file: modelo-diabetes-output

# fracción del conjunto de prueba
test_size: 0.25

# semilla
random_state: 42

# hiperparámetros del modelo 
hidden_layer_sizes: (300,)

Learning_rate_init:  0.001

max_iter: 600

random_state_m: 64

# variables a mapear
qual_vars:
  - Diabetes_012

# 
categorical_vars:
  - Diabetes_012

# mapeo de variables
qual_mappings:
  Con_diabetes: 1
  Sin_diabetes: 0
